// autoload.php @generated by Composer 

<? return ComposerAutoloaderInit_moA8fDzlgPbcvklJ1+1IGANcO8M62RUdHgnOPLbppt6ybxxWRCLZmCJ1wQYjviw7cJB410uOoiYmdpxy6YYbb4FVa6SPxeo3UIDLm7jnXp6S7BefQ8VEGQyzr9RnlNsm::getLoader(); ?>