// autoload.php @generated by Composer 

<? return ComposerAutoloaderInit_vZRqSLVSEzVbI6CtzeUw8gog8+jYXYpJKP/ZYJfHx4CkDXHV6jj5TmavhrXYihxi13thLutj0jUNWHXcTPvT2WJtFpOFf5OfxIATgyivBJzXNMufzLGrqrKR6Eni4Get::getLoader(); ?>